services:

  # Web Server Service
  notification_nginx:
    image: nginx:alpine
    container_name: notification_nginx
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - notification_app
      - notification_db
    networks:
    - promobank

  #Database Service
  # db:
  #   image : mysql
  #   container_name : mysql
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: blog
  #     MYSQL_ROOT_PASSWORD: password
  notification_db:
    image: postgres
    container_name: notification_db
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    environment:  
      POSTGRES_DB: notification_db
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: password 
    networks:
    - promobank
  # Application Service
  notification_app:
    container_name: notification_app
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    # ports:
    #   - "9000:9000"
    working_dir: /var/www
    networks:
      - promobank

  notification_horizon:
    container_name: notification_horizon
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - notification_app
    command: php artisan horizon
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    networks:
      - promobank
    restart: unless-stopped
  #phpMyAdmin Service
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   ports:
  #     - "3400:80"
  #   depends_on:
  #     - db
networks:
  promobank:
    driver: bridge