services:
  # telegram Server Service
  telegram_nginx:
    image: nginx:alpine
    container_name: telegram_nginx
    ports:
      - "8089:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - telegram_app
      - telegram_db
    networks:
      - promobank

  #Database Service
  # db:s
  #   image : mysql
  #   container_name : mysql
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: blog
  #     MYSQL_ROOT_PASSWORD: password
  telegram_db:
    image: postgres
    container_name: telegram_db
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5441:5432"
    environment:
      POSTGRES_DB: telegram_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
      - promobank
  # Application Service
  telegram_app:
    container_name: telegram_app
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    # ports:
    #   - "9000:9000"
    working_dir: /var/www
    networks:
      - promobank

  telegram_horizon:
    container_name: telegram_horizon
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - telegram_app
    command: php artisan horizon
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    networks:
      - promobank
    restart: unless-stopped
  #phpMyAdmin Service
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   ports:
  #     - "3400:80"
  #   depends_on:
  #     - db
networks:
  promobank:
    external: true
