version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./api-getaway:/var/www/api
      - ./auth-service:/var/www/auth
      - ./promo-service:/var/www/promo
      - ./media-service:/var/www/media
      - ./notification-service:/var/www/notification
      - ./certbot:/var/www/certbot
    depends_on:
      - api_app
      - auth_app
      - promo_app
      - media_app
      - notification_app
    networks:
      - promobank

  api_app:
    build:
      context: ./api-getaway/php
    container_name: api_app
    networks:
      - promobank
    expose:
      - "9000"

  auth_app:
    build:
      context: ./auth-service/php
    container_name: auth_app
    networks:
      - promobank
    expose:
      - "9000"

  promo_app:
    build:
      context: ./promo-service/php
    container_name: promo_app
    networks:
      - promobank
    expose:
      - "9000"

  media_app:
    build:
      context: ./media-service/php
    container_name: media_app
    networks:
      - promobank
    expose:
      - "9000"

  notification_app:
    build:
      context: ./notification-service/php
    container_name: notification_app
    networks:
      - promobank
    expose:
      - "9000"

networks:
  promobank:
    external: true