services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api_app
      - auth_app
      - promo_app
      - media_app
    networks:
      - promobank

  api_app:
    build:
      context: ./api-getaway/php
    container_name: api_app
    networks:
      - promobank

  auth_app:
    build:
      context: ./auth-service/php
    container_name: auth_app
    networks:
      - promobank

  promo_app:
    build:
      context: ./promo-service/php
    container_name: promo_app
    mem_limit: 1024m
    mem_reservation: 512m
    networks:
      - promobank

  media_app:
    build:
      context: ./media-service/php
    container_name: media_app
    networks:
      - promobank
  notification_app:
    build:
      context: ./notification-service/php
    container_name: notification_app
    networks:
      - promobank
  telegram_app:
    build:
      context: ./telegram-service/php
    container_name: telegram_app
    networks:
      - promobank

networks:
  promobank:
    external: true
