services:

  # profile Server Service
  profile_nginx:
    image: nginx:alpine
    container_name: profile_nginx
    ports:
      - "8087:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - profile_app
      - profile_db
    networks:
    - promobank

  #Database Service
  # db:
  #   image : mysql
  #   container_name : mysql
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: blog
  #     MYSQL_ROOT_PASSWORD: password
  profile_db:
    image: postgres:18
    container_name: profile_db
    volumes:
      - ./postgresql/data:/var/lib/postgresql/18/data
    ports:
      - "5439:5432"
    environment:  
      POSTGRES_DB: profile_db
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: password 
    networks:
    - promobank
  # Application Service
  profile_app:
    container_name: profile_app
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    # ports:
    #   - "9000:9000"
    working_dir: /var/www
    networks:
      - promobank

  profile_horizon:
    container_name: profile_horizon
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - profile_app
    command: php artisan horizon
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    networks:
      - promobank
    restart: unless-stopped
  #phpMyAdmin Service
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   ports:
  #     - "3400:80"
  #   depends_on:
  #     - db
networks:
  promobank:
    external: true