services:

  # Web Server Service
  payment_nginx:
    image: nginx:alpine
    container_name: payment_nginx
    ports:
      - "8084:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - payment_app
      - payment_db
    networks:
    - promobank

  #Database Service
  # db:
  #   image : mysql
  #   container_name : mysql
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: blog
  #     MYSQL_ROOT_PASSWORD: password
  payment_db:
    image: postgres
    container_name: payment_db
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:  
      POSTGRES_DB: payment_db
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: password 
    networks:
    - promobank
  # Application Service
  payment_app:
    container_name: payment_app
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    # ports:
    #   - "9000:9000"
    working_dir: /var/www
    networks:
      - promobank

  #phpMyAdmin Service
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   ports:
  #     - "3400:80"
  #   depends_on:
  #     - db
networks:
  promobank:
    driver: bridge