services:
  api_nginx:
    image: nginx:alpine
    container_name: api_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - api_app
      - api_db
    networks:
      - promobank

  #Database Service
  # db:
  #   image : mysql
  #   container_name : mysql
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: blog
  #     MYSQL_ROOT_PASSWORD: password
  api_db:
    image: postgres
    container_name: api_db
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
      - promobank
  # Application Service
  api_app:
    container_name: api_app
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
      - ../common:/var/www/common
    ports:
      - "9000:9000"
    working_dir: /var/www
    networks:
      - promobank

  api_horizon:
    container_name: api_horizon
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - api_app
    command: php artisan horizon
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    networks:
      - promobank
    restart: unless-stopped
  #phpMyAdmin Service
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   ports:
  #     - "3400:80"
  #   depends_on:
  #     - db
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgAdmin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - api_db
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: qadar@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   networks:c
  #     - promobank
networks:
  promobank:
    external: true
