services:

  api_db:
    image: postgres:18
    container_name: api_db
    volumes:
      - ./postgresql/data:/var/lib/postgresql/18/data
    ports:
      - "5432:5432"
    environment:  
      POSTGRES_DB: api_db
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: password 
    networks:
    - promobank
  # Application Service
  api_app:
    container_name: api_app
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    # ports:
    #   - "9000:9000"
    working_dir: /var/www
    networks:
      - promobank

  api_horizon:
    container_name: api_horizon
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - api_app
    command: php artisan horizon
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    networks:
      - promobank
    restart: unless-stopped
  #phpMyAdmin Service
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   ports:
  #     - "3400:80"
  #   depends_on:
  #     - db
  api_nginx:
    image: nginx:alpine
    container_name: api_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - /etc/letsencrypt:/etc/letsencrypt:ro         
 
    depends_on:
      - api_app
      - api_db
    networks:
    - promobank
networks:
  promobank:
    external: true